# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wZOFD-YfCiqJTVUzwKisbYkZSj0GBdLl
"""

# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# Load the data
data = pd.read_csv("/content/train.csv")
data_test = pd.read_csv("/content/test.csv")

# Extract features (X) and target variable (y)
X = data[['LotArea']]
y = data['SalePrice']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a linear regression model
model = LinearRegression()

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = model.predict(X_test)

# Plot predictions vs. actual values
plt.scatter(X_test, y_test, color='black', label='Actual Prices')
plt.scatter(X_test, y_pred, color='blue',  label='Predicted Prices')
plt.xlabel("LotArea")
plt.ylabel("SalePrice")
plt.title("Actual Prices vs. Predicted Prices")
plt.legend()
plt.show()